server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  # 数据库操作
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #日志
  logging:
    level:
      root: info
      top.wfaceboss: debug
    file: log/blog-test.log